Adds patches/20250331-stringhasher-arm64.
https://github.com/tommie/v8go/actions/runs/14162311946/job/39669655522

string-hasher.cc introduced in https://chromium-review.googlesource.com/c/v8/v8/+/6185430

```
2025-03-31T03:49:55.1091394Z ../../v8/src/strings/string-hasher.cc:32:56: error: cannot convert ‘int16x8_t’ to ‘uint16x8_t’
2025-03-31T03:49:55.1099422Z ../../v8/src/strings/string-hasher.cc:53:37: error: cannot convert ‘int8x8_t’ to ‘uint64x1_t’
2025-03-31T03:49:55.1104548Z ../../v8/src/strings/string-hasher.cc:54:56: error: cannot convert ‘int16x8_t’ to ‘uint16x8_t’
```